name: architech_drone_control_app
description: "ArchiTech - Drone Control App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_joystick: ^0.2.0
  get: ^4.6.6
  get_storage: ^2.1.1
  media_kit: ^1.1.9
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.2
  socket_io_client: ^2.0.3+1
  package_info_plus: ^8.0.0
  network_info_plus: ^5.0.3
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon.png"